name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: make -j"$(nproc)"

      - name: Run unit tests (produce JUnit)
        shell: bash
        run: |
          mkdir -p test-results
          # テスト失敗でも後続のアップロードを実行したいので || true を付ける
          tests/bin/unit --reporters=junit --out=test-results/unit.xml --no-skip || true

      - name: Upload test results
        if: always()              # 成功/失敗に関わらず成果物アップ
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: test-results
          retention-days: 14

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Check formatting
        shell: bash
        run: |
          FILES=$(find include src tests -type f \( -name '*.h' -o -name '*.hpp' -o -name '*.cpp' \))
          clang-format --dry-run --Werror $FILES
