name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 依存（g++, make など）※Runnerにだいたい入ってるが明示しておくと安心
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build
        run: make -j

      - name: Run unit tests
        run: make test
